### ISSUE TITLE
What gives a 3D voxel structure that's "coercible to an array"?

### ISSUE THREAD

**Issue by mavavilj** [jonclayden/mmand#7]
What gives a 3D voxel structure that's "coercible to an array"?

As required by e.g. morph?

**Comment by jonclayden** [comment]
That's a pretty open-ended question. What are you starting with? Some kind of image object? A file?

**Comment by mavavilj** [comment]
Well I'm working with this:

https://rdrr.io/cran/lidR/man/voxel_metrics.html

**Comment by jonclayden** [comment]
Thanks for clarifying. I'm not familiar with the `lidR` package, but that function appears to produce tabular data along the lines of some sparse representations. If the package doesn't provide an `as.array` method for its objects, or another way to convert them to array-type objects, you may need to wrangle the data into array form yourself.

**Comment by mavavilj** [comment]
What's the expected array like anyways?

**Comment by jonclayden** [comment]
The information is here, but it's not in the right form. You'd need to convert this to a dense three-dimensional array whose elements reflect the values of the metric at each location on the voxel grid. For example:

1. Create a vector of X locations between the maximum and minimum X values in the first column, in steps of 0.1. Repeat for Y and Z.
2. Create an array of zeros (presumably) with dimensions given by the lengths of those three vectors.
3. Insert the values from the fourth column at locations matching each voxel location.

**Comment by mavavilj** [comment]
I see.

Would be probably convenient to have a function that does automatic conversion from matrices and data.frames of XYZ + optional fourth dimension of data.

**Comment by jonclayden** [comment]
If sparse representations were quite standard across other packages that might be easy to arrange, but there is quite a bit of variation so it's difficult to do. The [`slam` package](https://cran.r-project.org/package=slam) does some conversion between a sparse array format that is similar to this and canonical dense arrays, but `lidR`'s format is a variation because it specifies locations in "real space" rather than integer indices.

There is nothing special about `mmand`'s format – the dense array is a core R data structure, so it's highly interoperable. I think it makes more sense for packages to provide `as.array` methods for their specialised array-like data structures. It might be worth asking the `lidR` package maintainer about adding one to that package.

**Comment by jonclayden** [comment]
I'm closing this issue as out of scope, because it seems to boil down to converting a third-party package's specialised format to a generic one.
